name: Test
on: [push]
jobs:
  Test:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Vlang
        uses: vlang/setup-v@v1.1
        with:
          version: 54b623743d12306aac8d0091daf3149299d5fe9e
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: v test .
